services:
  server:
    build:
      context: .
      target: dev
    ports:
      - 3001:3001
      - 9229:9229
    environment:
      NODE_ENV: development
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      POSTGRES_DB: example
    depends_on:
      db:
        condition: service_healthy
      
    secrets:
      - db-password
    volumes:
      - ./src:/usr/src/app/src
      - ./logs:/usr/src/app/logs
      - /usr/src/app/node_modules

  test:
    build:
      context: .
      target: test
    environment:
      NODE_ENV: test
    volumes:
      - ./src:/usr/src/app/src
      - ./tests:/usr/src/app/tests
      - ./jest.config.ts:/usr/src/app/jest.config.ts
      - ./jest.setup.ts:/usr/src/app/jest.setup.ts
      - ./tsconfig.jest.json:/usr/src/app/tsconfig.jest.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - /usr/src/app/node_modules
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD=securepassword
    expose:
      - 5432
    
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
